"""Add reviews table

Revision ID: 18c005a05eb7
Revises: 97dbea126c3e
Create Date: 2026-07-19 16:58:17.363696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18c005a05eb7'
down_revision: Union[str, Sequence[str], None] = '97dbea126c3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Добавляем столбец как nullable
    op.add_column('products', sa.Column('rating', sa.Float(), nullable=True))
    # 2. Заполняем рейтинг 0.0 для существующих товаров (чтобы не было NULL)
    op.execute("UPDATE products SET rating = 0.0 WHERE rating IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'rating')
    # ### end Alembic commands ###
