"""Create Search Vector

Revision ID: 30d728fb245f
Revises: 75d36abf517d
Create Date: 2026-08-02 17:45:01.790423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '30d728fb245f'
down_revision: Union[str, Sequence[str], None] = '75d36abf517d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("\n            setweight(to_tsvector('russian', coalesce(name, '')), 'A')\n            || \n            setweight(to_tsvector('russian', coalesce(description, '')), 'B')\n            ", persisted=True), nullable=False))
    op.create_index('ix_products_tsv_gin', 'products', ['tsv'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_tsv_gin', table_name='products', postgresql_using='gin')
    op.drop_column('products', 'tsv')
    # ### end Alembic commands ###
