"""add specs specifications

Revision ID: 5a8eac627a20
Revises: 800083da92b5
Create Date: 2026-08-17 17:55:27.397032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a8eac627a20'
down_revision: Union[str, Sequence[str], None] = '800083da92b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('specs', sa.JSON(), nullable=True))
    op.alter_column('products', 'tsv',
               existing_type=postgresql.TSVECTOR(),
               nullable=False,
               existing_server_default=sa.Computed('(setweight(to_tsvector(\'russian\'::regconfig, (COALESCE(name, \'\'::character varying))::text), \'A\'::"char") || setweight(to_tsvector(\'russian\'::regconfig, (COALESCE(description, \'\'::character varying))::text), \'B\'::"char"))', persisted=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'tsv',
               existing_type=postgresql.TSVECTOR(),
               nullable=True,
               existing_server_default=sa.Computed('(setweight(to_tsvector(\'russian\'::regconfig, (COALESCE(name, \'\'::character varying))::text), \'A\'::"char") || setweight(to_tsvector(\'russian\'::regconfig, (COALESCE(description, \'\'::character varying))::text), \'B\'::"char"))', persisted=True))
    op.drop_column('products', 'specs')
    # ### end Alembic commands ###
