"""Add user model

Revision ID: 5bb0336514eb
Revises: d6b88e384743
Create Date: 2026-07-15 16:14:47.685793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bb0336514eb'
down_revision: Union[str, Sequence[str], None] = 'd6b88e384743'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM products")
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emil', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_emil'), 'users', ['emil'], unique=True)
    op.add_column('products', sa.Column('seller_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'products', 'users', ['seller_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'seller_id')
    op.drop_index(op.f('ix_users_emil'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
