"""Changesinmodel_for_delete

Revision ID: c94eec8f7dff
Revises: 73cabb1f63b0
Create Date: 2026-08-02 20:32:18.464777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c94eec8f7dff'
down_revision: Union[str, Sequence[str], None] = '73cabb1f63b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
